{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"HR-Employee-Attrition\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-KE",
    "tables": [
      {
        "name": "HR-Employee-Attrition",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61ec4075-11f8-4641-8aaa-9af2f2c264dc",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Attrition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac63d420-04ee-4ad9-ba24-df258246b93e",
            "sourceColumn": "Attrition",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessTravel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c6815f2-5f94-4827-980e-51d6cef59fa6",
            "sourceColumn": "BusinessTravel",
            "summarizeBy": "none"
          },
          {
            "name": "DailyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ae1b9e49-6ade-4491-ba04-254e8dc04599",
            "sourceColumn": "DailyRate",
            "summarizeBy": "sum"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce0f6f53-cafe-4504-9c3e-cf0e03273653",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "DistanceFromHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "951d22f9-e2cc-47d9-a7fe-19dc45f393d1",
            "sourceColumn": "DistanceFromHome",
            "summarizeBy": "sum"
          },
          {
            "name": "Education",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4b97290-66cc-4b79-9abb-ef9553d37ae0",
            "sourceColumn": "Education",
            "summarizeBy": "sum"
          },
          {
            "name": "EducationField",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2fe6963-44c4-4f1f-9f15-c10df36e146c",
            "sourceColumn": "EducationField",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3467501-c988-494a-b0ae-29d415fce0ad",
            "sourceColumn": "EmployeeCount",
            "summarizeBy": "sum"
          },
          {
            "name": "EmployeeNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad002df8-ffdd-4879-be18-79adba9c04e2",
            "sourceColumn": "EmployeeNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "EnvironmentSatisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23957064-d2ff-489b-be92-2a2a4be93eb2",
            "sourceColumn": "EnvironmentSatisfaction",
            "summarizeBy": "sum"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e6e30ab-6ed3-481f-b0c2-49ffd79e2fc5",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "HourlyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6a58c29-aaee-4b01-ae17-2adf92fc8740",
            "sourceColumn": "HourlyRate",
            "summarizeBy": "sum"
          },
          {
            "name": "JobInvolvement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c8e0439-d411-47dd-93c5-51024cdcbcfa",
            "sourceColumn": "JobInvolvement",
            "summarizeBy": "sum"
          },
          {
            "name": "JobLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9eca95d8-db83-47c1-a15d-8e60caf8b008",
            "sourceColumn": "JobLevel",
            "summarizeBy": "sum"
          },
          {
            "name": "JobRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa022b6e-4ebe-42ce-bb53-e348ff8b8dfa",
            "sourceColumn": "JobRole",
            "summarizeBy": "none"
          },
          {
            "name": "JobSatisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f770cc2b-8e26-4554-9a15-25fbba7b5466",
            "sourceColumn": "JobSatisfaction",
            "summarizeBy": "sum"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff7e1112-7e1a-47b8-b5ef-1442ed8e44ab",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "MonthlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86357dd8-90cd-4457-9cb3-976d08e197a3",
            "sourceColumn": "MonthlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthlyRate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b335214d-6698-4172-a549-fde1fe5042b1",
            "sourceColumn": "MonthlyRate",
            "summarizeBy": "sum"
          },
          {
            "name": "NumCompaniesWorked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99b5955e-6183-4347-a831-ab1326fc4e88",
            "sourceColumn": "NumCompaniesWorked",
            "summarizeBy": "sum"
          },
          {
            "name": "Over18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc346c00-11fc-4616-87d1-f2be5982860d",
            "sourceColumn": "Over18",
            "summarizeBy": "none"
          },
          {
            "name": "OverTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29a7cd92-6086-4191-bf63-29125ff6998f",
            "sourceColumn": "OverTime",
            "summarizeBy": "none"
          },
          {
            "name": "PercentSalaryHike",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ab19942-ae4f-46cd-be7b-d55cdc44606d",
            "sourceColumn": "PercentSalaryHike",
            "summarizeBy": "sum"
          },
          {
            "name": "PerformanceRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82b95732-a552-4e1b-b438-ba5e63a2cc08",
            "sourceColumn": "PerformanceRating",
            "summarizeBy": "sum"
          },
          {
            "name": "RelationshipSatisfaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0118c003-3c8c-4b0f-ac42-14745a4f2b5d",
            "sourceColumn": "RelationshipSatisfaction",
            "summarizeBy": "sum"
          },
          {
            "name": "StandardHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f52516df-fabe-4bc2-af7b-fa5781db5a91",
            "sourceColumn": "StandardHours",
            "summarizeBy": "sum"
          },
          {
            "name": "StockOptionLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccaa7c50-6e9e-45a7-8860-eee41d70ba9f",
            "sourceColumn": "StockOptionLevel",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalWorkingYears",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a150751c-71ab-48e5-852f-21e2d3e428f6",
            "sourceColumn": "TotalWorkingYears",
            "summarizeBy": "sum"
          },
          {
            "name": "TrainingTimesLastYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "47f583cc-e171-4877-bd76-6e8562066c88",
            "sourceColumn": "TrainingTimesLastYear",
            "summarizeBy": "sum"
          },
          {
            "name": "WorkLifeBalance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "855585bd-c9ee-4501-8e08-647cf5ee42df",
            "sourceColumn": "WorkLifeBalance",
            "summarizeBy": "sum"
          },
          {
            "name": "YearsAtCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e623e86-e154-442c-bf94-38577435a51a",
            "sourceColumn": "YearsAtCompany",
            "summarizeBy": "sum"
          },
          {
            "name": "YearsInCurrentRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d5243b9-a5ea-4b64-8a1c-9047bc3246fc",
            "sourceColumn": "YearsInCurrentRole",
            "summarizeBy": "sum"
          },
          {
            "name": "YearsSinceLastPromotion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8da87d51-6268-4561-8b3d-e812c07aab60",
            "sourceColumn": "YearsSinceLastPromotion",
            "summarizeBy": "sum"
          },
          {
            "name": "YearsWithCurrManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7728a606-d002-4d29-8fa3-a4171783fff5",
            "sourceColumn": "YearsWithCurrManager",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "32dd7542-6ae3-4270-88cf-f74e450b414d",
        "partitions": [
          {
            "name": "HR-Employee-Attrition",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\HP\\Downloads\\Project 3 - HR Analytics-20231219T075247Z-001\\Project 3 - HR Analytics\\Data P3 MeriSKILL\\HR-Employee-Attrition.csv\"),[Delimiter=\",\", Columns=35, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Age\", Int64.Type}, {\"Attrition\", type text}, {\"BusinessTravel\", type text}, {\"DailyRate\", Int64.Type}, {\"Department\", type text}, {\"DistanceFromHome\", Int64.Type}, {\"Education\", Int64.Type}, {\"EducationField\", type text}, {\"EmployeeCount\", Int64.Type}, {\"EmployeeNumber\", Int64.Type}, {\"EnvironmentSatisfaction\", Int64.Type}, {\"Gender\", type text}, {\"HourlyRate\", Int64.Type}, {\"JobInvolvement\", Int64.Type}, {\"JobLevel\", Int64.Type}, {\"JobRole\", type text}, {\"JobSatisfaction\", Int64.Type}, {\"MaritalStatus\", type text}, {\"MonthlyIncome\", Int64.Type}, {\"MonthlyRate\", Int64.Type}, {\"NumCompaniesWorked\", Int64.Type}, {\"Over18\", type text}, {\"OverTime\", type text}, {\"PercentSalaryHike\", Int64.Type}, {\"PerformanceRating\", Int64.Type}, {\"RelationshipSatisfaction\", Int64.Type}, {\"StandardHours\", Int64.Type}, {\"StockOptionLevel\", Int64.Type}, {\"TotalWorkingYears\", Int64.Type}, {\"TrainingTimesLastYear\", Int64.Type}, {\"WorkLifeBalance\", Int64.Type}, {\"YearsAtCompany\", Int64.Type}, {\"YearsInCurrentRole\", Int64.Type}, {\"YearsSinceLastPromotion\", Int64.Type}, {\"YearsWithCurrManager\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_dbff7b11-8f88-473a-874d-565c08437ab0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "db4f9061-5e8c-48f6-84cb-0f0e385f0f34",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3eb3c0f-bb1f-436e-8bf7-91e2bd4a46e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24ce5e9b-1c66-4c4e-8938-b802ce7a2b43",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a51fc0aa-7df3-48da-9cf1-4a3f9eac37f1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2ae82574-dde1-4c54-92ec-aeb884061ca5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9e3c937f-a403-4768-9dd0-942370ee110d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ffc20f55-a419-4f50-9593-9937c09fb2e0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7ac23a05-584f-4a61-9298-20dcb8f118f6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2078c1b3-ae4a-4a84-93bb-4f8e144bed9f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5e71fd58-ce5d-47de-9b80-14ba32eee41b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "564a616e-4c1d-4f13-b9ea-dc560df8d427",
                "ordinal": 3
              }
            ],
            "lineageTag": "5dfa0d8f-79cc-4ff3-ab3a-6351267f8d4f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "047035f6-175b-445c-ac67-e6b1f8c7a9cd",
        "partitions": [
          {
            "name": "DateTableTemplate_dbff7b11-8f88-473a-874d-565c08437ab0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}